language:
- cpp
compiler:
- gcc
- clang

before_install:

# boost 1.55
#- sudo add-apt-repository ppa:apokluda/boost1.55 -y
#- sudo apt-get update

# cmake 3.0.2
- wget http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz
- tar xf *.tar.gz
- cd cmake-*
- ./configure
- make

install:
# cmake 3.2
- sudo make install
# boost 1.55
#- sudo apt-get install libboost1.55-dev

before_script:
- which cmake
- cmake --version
- cd ..

script:
- mkdir _builds
- cd _builds
- cmake -Dbuild_tests=ON ..
# - make
# - ctest
