language:
- cpp
compiler:
- gcc
- clang

# cmake 3.2
before_install:
- wget http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz
- tar xf *.tar.gz
- cd cmake-*
- ./configure
- make
install:
- sudo make install

# boost 1.55
before_install:
- sudo add-apt-repository ppa:apokluda/boost1.55 -y
- sudo apt-get update
install:
- sudo apt-get install libboost1.55-dev

before_script:
- which cmake
- cmake --version
- cd ..

script:
- mkdir _builds
- cd _builds
- cmake -Dbuild_tests=ON ..
# - make
# - ctest
