language:
- cpp
compiler:
- gcc
- clang

before_install:

# boost 1.55
- sudo add-apt-repository ppa:ostogvin/tjo-develop/boost1.55 -y
- sudo apt-get update

# cmake 3.0.2
- sudo add-apt-repository -y ppa:andykimpe/cmake3
- sudo apt-get update

install:
# cmake 3.2
- sudo apt-get -y install cmake3
# boost 1.55
- sudo apt-get install libboost1.55-dev

before_script:
- which cmake
- cmake --version
- cd ..

script:
- mkdir _builds
- cd _builds
- cmake -Dbuild_tests=ON ..
# - make
# - ctest
