language:
- cpp
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository ppa:apokluda/boost1.55 -y
- sudo apt-get update
install:
- sudo apt-get install libboost1.55-dev
script:
- mkdir _builds
- cd _builds
- cmake ..
# - make
# - ctest