
language: cpp

compiler:
- gcc
- clang

os:
- linux
# - osx

branches:
only:
- master
- /^(?i:dev)-.*$/ # matches Dev-cmake and other branches and tags that start with dev- in any combination of cases.
- /^(?i:release)-.*$/ # matches release-0.10 and other branches and tags that start with release- in any combination of cases.

before_install:

# Add software package repository, containing updated build toochain, i.e. GNU GCC 4.8
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
- sudo add-apt-repository -y ppa:chewing/travis-ci/cmake # cmake 3.02 
- sudo add-apt-repository -y ppa:boost-latest/ppa  
# - sudo add-apt-repository -y ppa:ostogvin/tjo-develop
- sudo add-apt-repository -y ppa:beineri/opt-qt521 # qt 5.2
- sudo apt-get update -qq

install:

# upgrade compiler to g++4.8.1

- sudo apt-get install -y -qq gcc-4.8 g++-4.8 

- if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90 ; fi 
- if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/g++-4.8 90 ; fi 
- if [ "$CXX" = "g++" ]; then sudo apt-get install libstdc++-4.8-dev ; fi 
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi 

# install boost, cmake 

#- sudo apt-get install -y -qq gcc-4.8 g++-4.8 cmake-data cmake libboost1.55-all-dev 
- sudo apt-get install -y -qq gcc-4.8 g++-4.8 cmake-data cmake 

# Install newer boost compatible with gcc 4.8.
- g++ -v
- wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
- export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
- export CMAKE_MODULE_PATH="$BOOST_ROOT"
- mkdir -p $BOOST_ROOT
- tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
- (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=system,thread,coroutine,context )
- (cd $BOOST_ROOT; ./b2 cxxflags="-std=c++11" threading=multi --prefix=$BOOST_ROOT -d0 install)

# install qt 5.2 

- sudo apt-get install -y -qq qt52base qt52webkit qt52tools 
- export CMAKE_PREFIX_PATH="/opt/qt52/lib/cmake"
- ls /opt/qt52/lib/cmake 

before_script:

#report version 
- which cmake
- cmake --version
- g++ -v
- clang -v

script:
- mkdir _builds
- cd _builds
- cmake -Dbuild_tests=ON -Dbuild_coasync4qt=ON DCMAKE_PREFIX_PATH=/opt/qt52/lib/cmake .. 
# - make 
- make VERBOSE=1 
# - ctest

after_success:
- echo ########## success ##############
# trigger rebui ... 
after_failure: "cat ./bootstrap.log" 
- echo ########## bootstrap.log ##############
- cat ./bootstrap.log 
- echo ##########  g++ version ###############
- g++ -v

after_script:
- echo ########?? bootstrap.log ##############
- cat ./bootstrap.log 
- echo ##########  g++ version ###############
- g++ -v

